auth:
  # Define the default database user and password
  username: welltrackuser
  password: "replace-with-strong-password"  # TODO: Replace with a strong password, ideally manage with Vault later
  # Define the default database name
  database: welltrackdb

# Configuration for the primary PostgreSQL instance
primary:
  persistence:
    # Enable persistent storage for the primary instance
    enabled: true
    # Specify the StorageClass for the PersistentVolumeClaim
    storageClass: "standard"  # Using Kind's default SC, consider switching to Ceph later
    # Define the size of the persistent volume
    size: 5Gi
  # Define resource requests for the primary PostgreSQL pod
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

# Configuration for read replicas (disabled)
readReplicas:
  enabled: false

# Configuration for the PostgreSQL service
service:
  # Use ClusterIP for internal cluster access only
  type: ClusterIP