apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.0
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  mgr:
    count: 1
    allowMultiplePerNode: true
  dashboard:
    enabled: true
  crashCollector:
    disable: false
  storage:
    useAllNodes: true
    useAllDevices: false
    config:
      storeType: bluestore
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
    storageClassDeviceSets:
    - name: set1
      count: 1
      portable: false
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 1Gi
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
          volumeMode: Block
          accessModes:
          - ReadWriteOnce
  resources:
    mon:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        memory: "512Mi"
    mgr:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        memory: "512Mi"