deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  # Definir un esquema para Loki
  schemaConfig:
    configs:
      - from: 2023-01-01
        store: tsdb
        object_store: filesystem
        schema: v12
        index:
          prefix: index_
          period: 24h